import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import YAML from "yaml"
import { detectProject } from "./detector.ts"
import { generateYaml } from "./yaml-generator.ts"

const ADOPT_CANDIDATES = [
  "AGENTS.md",
  "CLAUDE.md",
  ".cursorrules",
  ".github/copilot-instructions.md",
  "GEMINI.md",
]

export interface AdoptResult {
  sourceFile: string | null
  yamlPath: string
  createdYaml: boolean
  appendedInstructions: boolean
  message: string
}

function pickBestSource(root: string, preferred?: string): string | null {
  if (preferred) {
    const p = resolve(root, preferred)
    if (existsSync(p)) return p
  }
  let best: { path: string; len: number } | null = null
  for (const rel of ADOPT_CANDIDATES) {
    const full = join(root, rel)
    if (!existsSync(full)) continue
    try {
      const len = readFileSync(full, "utf-8").trim().length
      if (!best || len > best.len) best = { path: full, len }
    } catch {
      continue
    }
  }
  return best?.path ?? null
}

/**
 * Import existing editor instruction files into universal-agent.yaml
 * without destroying portable memory. Relative paths only.
 */
export function adoptProject(
  targetDir: string,
  opts: { source?: string; forceYaml?: boolean } = {},
): AdoptResult {
  const root = resolve(targetDir)
  const yamlPath = join(root, "universal-agent.yaml")
  const sourcePath = pickBestSource(root, opts.source)

  if (!sourcePath) {
    return {
      sourceFile: null,
      yamlPath,
      createdYaml: false,
      appendedInstructions: false,
      message: "No adoptable instruction file found (AGENTS.md, CLAUDE.md, .cursorrules, …)",
    }
  }

  const imported = readFileSync(sourcePath, "utf-8").trim()
  const block = [
    "",
    "# --- adopted from existing editor instructions ---",
    imported,
    "# --- end adopted ---",
    "",
  ].join("\n")

  let createdYaml = false
  if (!existsSync(yamlPath) || opts.forceYaml) {
    const project = detectProject(root)
    const config = generateYaml(project)
    const existing = config.universal_instructions ?? ""
    config.universal_instructions = `${existing}\n${block}`.trim()
    const header = [
      "# =============================================",
      `# universal-agent.yaml — ${project.name}`,
      "# Generated by uagent adopt",
      "# Edit this file, then run: uagent generate",
      "# =============================================",
      "",
    ].join("\n")
    writeFileSync(yamlPath, header + YAML.stringify(config, { indent: 2, lineWidth: 120 }), "utf-8")
    createdYaml = true
    return {
      sourceFile: sourcePath,
      yamlPath,
      createdYaml,
      appendedInstructions: true,
      message: `Created universal-agent.yaml from detection + adopted ${sourcePath}`,
    }
  }

  // Append into existing YAML as universal_instructions addition (text-safe)
  let raw = readFileSync(yamlPath, "utf-8")
  if (raw.includes("# --- adopted from existing editor instructions ---")) {
    return {
      sourceFile: sourcePath,
      yamlPath,
      createdYaml: false,
      appendedInstructions: false,
      message: "universal-agent.yaml already contains an adopt block — skipped",
    }
  }

  if (/^universal_instructions:\s*\|/m.test(raw)) {
    raw = raw.replace(
      /^(universal_instructions:\s*\|[^\n]*\n)/m,
      `$1${block.split("\n").map((l) => (l.length ? `  ${l}` : "")).join("\n")}\n`,
    )
  } else {
    raw += `\nuniversal_instructions: |\n${block.split("\n").map((l) => `  ${l}`).join("\n")}\n`
  }

  writeFileSync(yamlPath, raw, "utf-8")
  return {
    sourceFile: sourcePath,
    yamlPath,
    createdYaml: false,
    appendedInstructions: true,
    message: `Appended adopt block from ${sourcePath} into universal-agent.yaml`,
  }
}
