<<<<<<< HEAD
import { writeFileSync, mkdirSync, existsSync, readFileSync, renameSync } from "node:fs"
import { join } from "node:path"
import type { DetectedProject } from "./detector.ts"

/** Canonical portable handoff at project root (survives folder/machine moves). */
export const CANONICAL_MEMORY_FILE = "PROJECT_MEMORY.md"

/** Legacy Spanish filename — migrate to canonical before seeding empty memory. */
export const LEGACY_MEMORY_FILES = ["MEMORIA_PROYECTO.md"] as const

=======
<<<<<<< HEAD
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import type { DetectedProject } from "./detector.ts"

/** Canonical portable handoff at project root (survives folder/machine moves). */
export const CANONICAL_MEMORY_FILE = "MEMORIA_PROYECTO.md"

=======
import { writeFileSync, mkdirSync, existsSync } from "node:fs"
import { join } from "node:path"
import type { DetectedProject } from "./detector.ts"

>>>>>>> ea657247f25059f94102155518e1f7eb9392381c
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
export interface MemoryFile {
  path: string
  content: string
}

<<<<<<< HEAD
function createProjectMemorySeed(project: DetectedProject): string {
=======
<<<<<<< HEAD
function createMemoriaProyectoSeed(project: DetectedProject): string {
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
  const stackBits: string[] = []
  if (project.languages.length) stackBits.push(`Languages: ${project.languages.join(", ")}`)
  if (project.frameworks.length) stackBits.push(`Frameworks: ${project.frameworks.join(", ")}`)
  if (project.runtime.length) stackBits.push(`Runtime: ${project.runtime.join(", ")}`)
  if (project.databases.length) stackBits.push(`Databases: ${project.databases.join(", ")}`)
<<<<<<< HEAD
=======

  return [
    "# Memoria del proyecto (canónica)",
    "",
    "**Fuente única** de handoff entre sesiones, equipos e IAs. Viaja con el repositorio",
    "(cualquier carpeta o unidad). No sustituye el plan maestro ni la documentación operativa.",
    "",
    `| Relacionado | Rol |`,
    `|-------------|-----|`,
    `| \`AGENTS.md\` | Reglas del agente / loop; debe leer y actualizar **este** archivo |`,
    `| \`.uagent/memory/\` | Stubs que apuntan aquí (multi-agente / uagent) |`,
    "",
    `**Proyecto:** ${project.name}`,
    "",
    stackBits.length ? `**Stack detectado:** ${stackBits.join(" · ")}` : "",
    "",
    `**Última actualización:** ${new Date().toISOString().slice(0, 10)} (init uagent)`,
    "",
    "---",
    "",
    "## Pendientes",
    "",
    "_Listar aquí lo abierto para la siguiente sesión._",
    "",
    "## Estado reciente",
    "",
    "_Tras cada entrega sustantiva: 1 párrafo + archivos clave tocados._",
    "",
    "### Cómo actualizar",
    "",
    "Fecha, pendientes si cambian, resumen breve. No duplicar runbooks ni el changelog del plan.",
    "",
  ]
    .filter((line, i, arr) => !(line === "" && arr[i - 1] === ""))
    .join("\n")
}

function stubContext(): string {
  return [
    "# Project Context (stub)",
    "",
    "La memoria canónica del proyecto está en la **raíz del repositorio**:",
    "",
    `**[\`${CANONICAL_MEMORY_FILE}\`](../../${CANONICAL_MEMORY_FILE})**`,
    "",
    "No escriba el handoff aquí. Actualice siempre ese archivo.",
    "Esta carpeta `.uagent/memory/` existe para el loop multi-agente (uagent); los archivos son punteros.",
    "",
  ].join("\n")
}

function stubDecisions(): string {
  return [
    "# Decisions Log (stub)",
    "",
    `Decisiones de producto/arquitectura: plan maestro del proyecto y, si aplica, notas en`,
    `**[\`${CANONICAL_MEMORY_FILE}\`](../../${CANONICAL_MEMORY_FILE})**.`,
    "",
    "No mantenga un segundo diario aquí.",
    "",
  ].join("\n")
}

function stubSessionLog(): string {
  return [
    "# Session Log (stub)",
    "",
    `Handoff entre sesiones: **[\`${CANONICAL_MEMORY_FILE}\`](../../${CANONICAL_MEMORY_FILE})** (raíz del repo).`,
    "",
    "Opcional: anotar un renglón aquí **además** de actualizar la memoria canónica, nunca en su lugar.",
    "",
  ].join("\n")
}

function stubAgent(agentName: string): string {
  return [
    `# Agent: ${agentName} (stub)`,
    "",
    `Memoria compartida del proyecto: **[\`${CANONICAL_MEMORY_FILE}\`](../../../${CANONICAL_MEMORY_FILE})**.`,
    "",
=======
function createContextFile(project: DetectedProject): string {
  const lines = [
    "# Project Context",
    "",
    `> Auto-generated by uagent init for: **${project.name}**`,
    "",
    "## Stack",
    "",
  ]
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406

  return [
    "# Project memory (canonical)",
    "",
    "**Single source of truth** for handoff across sessions, teams, and AI tools.",
    "Travels with the repository (any folder or drive). Does not replace the master plan or ops docs.",
    "",
    `| Related | Role |`,
    `|---------|------|`,
    `| \`AGENTS.md\` | Agent / loop rules; must read and update **this** file |`,
    `| \`.uagent/memory/\` | Stubs that point here (multi-agent / uagent) |`,
    "",
    `**Project:** ${project.name}`,
    "",
    stackBits.length ? `**Detected stack:** ${stackBits.join(" · ")}` : "",
    "",
    `**Last updated:** ${new Date().toISOString().slice(0, 10)} (uagent init)`,
    "",
    "---",
    "",
    "## Phases",
    "",
    "_Ordered delivery checklist. Mark `[x]` only after Definition of Done for that phase._",
    "",
    "**Definition of Done (each phase):** code in place → tests/checks pass → note key paths → mark `[x]` → next phase.",
    "",
    "- [ ] Phase 1 — _title_",
    "- [ ] Phase 2 — _title_",
    "- [ ] Phase 3 — _title_",
    "",
    "## Current phase",
    "",
    "_Name of the phase in progress, or `none` if idle/complete._",
    "",
    "## In progress",
    "",
    "_What is actively being built right now._",
    "",
    "## Blocked",
    "",
    "_Secrets, ambiguity, or irreversible decisions waiting on the user — or `none`._",
    "",
    "## Open items",
    "",
    "_List work left open for the next session._",
    "",
    "## Recent status",
    "",
    "_After each phase: 1 paragraph + key paths touched. On resume, start from the first unchecked phase._",
    "",
    "### How to update",
    "",
    "Date, current phase, checkboxes, blockers, short summary. Do not duplicate runbooks or the plan changelog.",
    "",
  ]
    .filter((line, i, arr) => !(line === "" && arr[i - 1] === ""))
    .join("\n")
}

function stubContext(): string {
  return [
    "# Project Context (stub)",
    "",
    "Canonical project memory lives at the **repository root**:",
    "",
    `**[\`${CANONICAL_MEMORY_FILE}\`](../../${CANONICAL_MEMORY_FILE})**`,
    "",
    "Do not write the handoff here. Always update that file.",
    "This `.uagent/memory/` folder exists for the multi-agent loop (uagent); files are pointers only.",
    "",
  ].join("\n")
}

function stubDecisions(): string {
  return [
    "# Decisions Log (stub)",
    "",
    `Product/architecture decisions: project master plan and, if needed, notes in`,
    `**[\`${CANONICAL_MEMORY_FILE}\`](../../${CANONICAL_MEMORY_FILE})**.`,
    "",
    "Do not keep a second diary here.",
    "",
  ].join("\n")
}

function stubSessionLog(): string {
  return [
    "# Session Log (stub)",
    "",
    `Session handoff: **[\`${CANONICAL_MEMORY_FILE}\`](../../${CANONICAL_MEMORY_FILE})** (repo root).`,
    "",
    "Optional: add one line here **in addition to** updating canonical memory, never instead of it.",
    "",
  ].join("\n")
}

function stubAgent(agentName: string): string {
  return [
    `# Agent: ${agentName} (stub)`,
    "",
    `Shared project memory: **[\`${CANONICAL_MEMORY_FILE}\`](../../../${CANONICAL_MEMORY_FILE})**.`,
    "",
<<<<<<< HEAD
=======
    "_No decisions recorded yet._",
>>>>>>> ea657247f25059f94102155518e1f7eb9392381c
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
  ].join("\n")
}

function createIndexFile(project: DetectedProject): string {
  return JSON.stringify(
    {
<<<<<<< HEAD
      version: "1.2.0",
      project: project.name,
      canonicalMemory: CANONICAL_MEMORY_FILE,
      note: "Canonical handoff lives at repo root. Files under .uagent/memory/ are stubs only.",
=======
<<<<<<< HEAD
      version: "1.1.0",
      project: project.name,
      canonicalMemory: CANONICAL_MEMORY_FILE,
      note: "Canonical handoff lives at repo root. Files under .uagent/memory/ are stubs only.",
=======
      version: "1.0.0",
      project: project.name,
>>>>>>> ea657247f25059f94102155518e1f7eb9392381c
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
      created: new Date().toISOString(),
      lastSession: null,
      sessions: [],
      agents: {},
    },
    null,
    2,
  )
}

<<<<<<< HEAD
=======
<<<<<<< HEAD
export function getMemoryFiles(project: DetectedProject): MemoryFile[] {
  return [
    { path: "context.md", content: stubContext() },
    { path: "decisions.md", content: stubDecisions() },
    { path: "index.json", content: createIndexFile(project) },
    { path: "session-log.md", content: stubSessionLog() },
    { path: "agents/core.md", content: stubAgent("core") },
  ]
}

/** Create root MEMORIA_PROYECTO.md only if missing (never overwrite). */
export function ensureCanonicalMemory(targetDir: string, project: DetectedProject): void {
  const memoriaPath = join(targetDir, CANONICAL_MEMORY_FILE)
  if (existsSync(memoriaPath)) {
    console.log(`  ${CANONICAL_MEMORY_FILE} already exists — left unchanged`)
    return
  }
  writeFileSync(memoriaPath, createMemoriaProyectoSeed(project), "utf-8")
  console.log(`  Created ${CANONICAL_MEMORY_FILE} (canonical portable memory)`)
}

export function initMemory(targetDir: string, project: DetectedProject): void {
  ensureCanonicalMemory(targetDir, project)

  const memoryDir = join(targetDir, ".uagent", "memory")
=======
function createSessionLogTemplate(): string {
  return [
    "# Session Log",
    "",
    "> Auto-created at session start. Agents append to this file.",
    "",
    "## Format",
    "",
    "```",
    "### [YYYY-MM-DD HH:MM] Session Title",
    "",
    "- **Agent:** agent-name",
    "- **Task:** what was being worked on",
    "- **Status:** completed / in-progress / blocked",
    "- **Changes:** files modified, commands run",
    "- **Notes:** anything relevant for future sessions",
    "```",
    "",
    "## Sessions",
    "",
    "_No sessions recorded yet._",
  ].join("\n")
}

function createAgentMemoryTemplate(agentName: string): string {
  return [
    `# Agent: ${agentName}`,
    "",
    `> Memory specific to the "${agentName}" agent.`,
    "",
    "## Context",
    "",
    "_What this agent knows about its domain._",
    "",
    "## Files Owned",
    "",
    "_Files this agent is responsible for._",
    "",
    "## Recent Changes",
    "",
    "_Last modifications made by this agent._",
    "",
    "---",
    "",
    "_Updated automatically during sessions._",
  ].join("\n")
}

>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
export function getMemoryFiles(project: DetectedProject): MemoryFile[] {
  return [
    { path: "context.md", content: stubContext() },
    { path: "decisions.md", content: stubDecisions() },
    { path: "index.json", content: createIndexFile(project) },
    { path: "session-log.md", content: stubSessionLog() },
    { path: "agents/core.md", content: stubAgent("core") },
  ]
}

/**
 * Create root PROJECT_MEMORY.md only if missing (never overwrite).
 * If a legacy memory file exists, rename it instead of seeding empty content
 * (avoids init → upgrade --prune deleting real handoff).
 */
export function ensureCanonicalMemory(targetDir: string, project: DetectedProject): void {
  const memoryPath = join(targetDir, CANONICAL_MEMORY_FILE)
  if (existsSync(memoryPath)) {
    console.log(`  ${CANONICAL_MEMORY_FILE} already exists — left unchanged`)
    return
  }

  for (const legacy of LEGACY_MEMORY_FILES) {
    const legacyPath = join(targetDir, legacy)
    if (!existsSync(legacyPath)) continue
    renameSync(legacyPath, memoryPath)
    console.log(`  Migrated ${legacy} → ${CANONICAL_MEMORY_FILE}`)
    return
  }

  writeFileSync(memoryPath, createProjectMemorySeed(project), "utf-8")
  console.log(`  Created ${CANONICAL_MEMORY_FILE} (canonical portable memory)`)
}

export function initMemory(targetDir: string, project: DetectedProject): void {
  ensureCanonicalMemory(targetDir, project)

<<<<<<< HEAD
  const memoryDir = join(targetDir, ".uagent", "memory")
=======
>>>>>>> ea657247f25059f94102155518e1f7eb9392381c
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true })
  }

  const agentsDir = join(memoryDir, "agents")
  if (!existsSync(agentsDir)) {
    mkdirSync(agentsDir, { recursive: true })
  }

  const files = getMemoryFiles(project)
  for (const file of files) {
    const filePath = join(memoryDir, file.path)
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
    const parts = file.path.split("/")
    if (parts.length > 1) {
      const dir = join(memoryDir, ...parts.slice(0, -1))
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    }
<<<<<<< HEAD
=======
    writeFileSync(filePath, file.content, "utf-8")
  }

  console.log(`  Created .uagent/memory/ stubs → ${CANONICAL_MEMORY_FILE} (${files.length} files)`)
}

export function ensureMemory(targetDir: string, project: DetectedProject): void {
  ensureCanonicalMemory(targetDir, project)

  const memoryDir = join(targetDir, ".uagent", "memory")
  const indexPath = join(memoryDir, "index.json")
  if (!existsSync(memoryDir) || !existsSync(indexPath)) {
    initMemory(targetDir, project)
    return
  }

  try {
    const raw = readFileSync(indexPath, "utf-8")
    const idx = JSON.parse(raw) as { canonicalMemory?: string }
    if (idx.canonicalMemory !== CANONICAL_MEMORY_FILE) {
      writeFileSync(indexPath, createIndexFile(project), "utf-8")
      writeFileSync(join(memoryDir, "context.md"), stubContext(), "utf-8")
      console.log(`  Updated .uagent/memory stubs to point at ${CANONICAL_MEMORY_FILE}`)
    }
  } catch {
    initMemory(targetDir, project)
=======
    const dir = join(memoryDir, file.path.split("/").slice(0, -1).join("/"))
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
    writeFileSync(filePath, file.content, "utf-8")
  }

  console.log(`  Created .uagent/memory/ stubs → ${CANONICAL_MEMORY_FILE} (${files.length} files)`)
}

export function ensureMemory(targetDir: string, project: DetectedProject): void {
  ensureCanonicalMemory(targetDir, project)

  const memoryDir = join(targetDir, ".uagent", "memory")
  const indexPath = join(memoryDir, "index.json")
  if (!existsSync(memoryDir) || !existsSync(indexPath)) {
    initMemory(targetDir, project)
    return
  }

  try {
    const raw = readFileSync(indexPath, "utf-8")
    const idx = JSON.parse(raw) as { canonicalMemory?: string }
    if (idx.canonicalMemory !== CANONICAL_MEMORY_FILE) {
      writeFileSync(indexPath, createIndexFile(project), "utf-8")
      writeFileSync(join(memoryDir, "context.md"), stubContext(), "utf-8")
      console.log(`  Updated .uagent/memory stubs to point at ${CANONICAL_MEMORY_FILE}`)
    }
<<<<<<< HEAD
  } catch {
    initMemory(targetDir, project)
=======
>>>>>>> ea657247f25059f94102155518e1f7eb9392381c
>>>>>>> 22bb3ef495b2b824adfa337c84e9d44877d80406
  }
}
