import { writeFileSync, mkdirSync, existsSync } from "node:fs"
import { join } from "node:path"
import type { DetectedProject } from "./detector.ts"

export interface MemoryFile {
  path: string
  content: string
}

function createContextFile(project: DetectedProject): string {
  const lines = [
    "# Project Context",
    "",
    `> Auto-generated by uagent init for: **${project.name}**`,
    "",
    "## Stack",
    "",
  ]

  if (project.languages.length) lines.push(`- **Languages:** ${project.languages.join(", ")}`)
  if (project.frameworks.length) lines.push(`- **Frameworks:** ${project.frameworks.join(", ")}`)
  if (project.runtime.length) lines.push(`- **Runtime:** ${project.runtime.join(", ")}`)
  if (project.packageManagers.length) lines.push(`- **Package Managers:** ${project.packageManagers.join(", ")}`)
  if (project.databases.length) lines.push(`- **Databases:** ${project.databases.join(", ")}`)

  lines.push(
    "",
    "## Project Structure",
    "",
    "_Document the project structure here as you work._",
    "",
    "## Key Files",
    "",
    "_List important files and their purposes._",
    "",
    "---",
    "",
    "_This file is updated by agents during sessions._",
  )

  return lines.join("\n")
}

function createDecisionsFile(): string {
  return [
    "# Decisions Log",
    "",
    "> Track architectural and design decisions here.",
    "",
    "## Format",
    "",
    "```",
    "### [DATE] Decision Title",
    "",
    "- **Context:** Why this decision was needed",
    "- **Decision:** What was decided",
    "- **Alternatives:** What was considered",
    "- **Consequences:** What this means for the project",
    "```",
    "",
    "## Decisions",
    "",
    "_No decisions recorded yet._",
  ].join("\n")
}

function createIndexFile(project: DetectedProject): string {
  return JSON.stringify(
    {
      version: "1.0.0",
      project: project.name,
      created: new Date().toISOString(),
      lastSession: null,
      sessions: [],
      agents: {},
    },
    null,
    2,
  )
}

function createSessionLogTemplate(): string {
  return [
    "# Session Log",
    "",
    "> Auto-created at session start. Agents append to this file.",
    "",
    "## Format",
    "",
    "```",
    "### [YYYY-MM-DD HH:MM] Session Title",
    "",
    "- **Agent:** agent-name",
    "- **Task:** what was being worked on",
    "- **Status:** completed / in-progress / blocked",
    "- **Changes:** files modified, commands run",
    "- **Notes:** anything relevant for future sessions",
    "```",
    "",
    "## Sessions",
    "",
    "_No sessions recorded yet._",
  ].join("\n")
}

function createAgentMemoryTemplate(agentName: string): string {
  return [
    `# Agent: ${agentName}`,
    "",
    `> Memory specific to the "${agentName}" agent.`,
    "",
    "## Context",
    "",
    "_What this agent knows about its domain._",
    "",
    "## Files Owned",
    "",
    "_Files this agent is responsible for._",
    "",
    "## Recent Changes",
    "",
    "_Last modifications made by this agent._",
    "",
    "---",
    "",
    "_Updated automatically during sessions._",
  ].join("\n")
}

export function getMemoryFiles(project: DetectedProject): MemoryFile[] {
  const files: MemoryFile[] = [
    { path: "context.md", content: createContextFile(project) },
    { path: "decisions.md", content: createDecisionsFile() },
    { path: "index.json", content: createIndexFile(project) },
    { path: "session-log.md", content: createSessionLogTemplate() },
    { path: "agents/core.md", content: createAgentMemoryTemplate("core") },
  ]

  return files
}

export function initMemory(targetDir: string, project: DetectedProject): void {
  const memoryDir = join(targetDir, ".uagent", "memory")

  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true })
  }

  const agentsDir = join(memoryDir, "agents")
  if (!existsSync(agentsDir)) {
    mkdirSync(agentsDir, { recursive: true })
  }

  const files = getMemoryFiles(project)
  for (const file of files) {
    const filePath = join(memoryDir, file.path)
    const dir = join(memoryDir, file.path.split("/").slice(0, -1).join("/"))
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileSync(filePath, file.content, "utf-8")
  }

  console.log(`  Created .uagent/memory/ with ${files.length} files`)
}

export function ensureMemory(targetDir: string, project: DetectedProject): void {
  const memoryDir = join(targetDir, ".uagent", "memory")
  if (!existsSync(memoryDir)) {
    initMemory(targetDir, project)
  } else {
    const indexPath = join(memoryDir, "index.json")
    if (!existsSync(indexPath)) {
      initMemory(targetDir, project)
    }
  }
}
